/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#005185",
        "surface-variant": "#e1e3e1",
        "status-review": "#F59E0B",
        "tertiary": "#793f00",
        "breaking-red": "#E31212",
        "surface-container-low": "#f3f4f2",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e1e3e1",
        "on-background": "#191c1b",
        "on-secondary": "#ffffff",
        "background": "#f9faf8",
        "surface-container-high": "#e7e8e6",
        "tertiary-container": "#9c5300",
        "on-tertiary-fixed": "#2f1500",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#9bcbff",
        "inverse-primary": "#9bcbff",
        "surface-tint": "#00629f",
        "status-scheduled": "#8B5CF6",
        "status-published": "#10B981",
        "status-draft": "#6B7280",
        "tertiary-fixed-dim": "#ffb77e",
        "primary-fixed": "#d0e4ff",
        "secondary-fixed-dim": "#c8c6c5",
        "outline": "#717881",
        "tertiary-fixed": "#ffdcc3",
        "inverse-surface": "#2e3130",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#edeeec",
        "secondary-fixed": "#e5e2e1",
        "on-primary-fixed-variant": "#004a7a",
        "on-surface-variant": "#414750",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1b",
        "on-tertiary-container": "#ffdfc8",
        "on-secondary-fixed": "#1c1b1b",
        "secondary-container": "#e5e2e1",
        "surface-bright": "#f9faf8",
        "surface": "#f9faf8",
        "secondary": "#5f5e5e",
        "on-tertiary-fixed-variant": "#6e3900",
        "error": "#ba1a1a",
        "outline-variant": "#c0c7d2",
        "inverse-on-surface": "#f0f1ef",
        "surface-card": "#FFFFFF",
        // Helper classes
        "primary-container": "#005185", // Primary theme containers
        "on-primary-container": "#ffffff",
      },
      borderRadius: {
        "default": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "stack-sm": "8px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "status-label": ["Inter", "sans-serif"],
        "headline-md-mobile": ["Source Serif 4", "serif"],
        "display-lg": ["Source Serif 4", "serif"],
        "headline-sm": ["Source Serif 4", "serif"],
        "label-caps": ["Epilogue", "sans-serif"],
        "headline-md": ["Source Serif 4", "serif"],
        "display-lg-mobile": ["Source Serif 4", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
